### ISSUE TITLE
SL schedule input

### ISSUE THREAD

**Issue by ctheil** [LRC-devops/lrc-site-repo#95]
under the sp22_sl-sched branch (si.html page), replace all existing sessions in the schedule (found at the bottom of the page above the </main> and <script> tags) with the information found in [this document.](https://www.dropbox.com/s/qnjaofc38lltrin/SL%20Spring%2022%20Schedule.pdf?dl=0)

**Comment by nataliejschultz** [comment]
Just created a pull request for this. Let me know if it needs any alterations!
